sudo: required
services:
- docker
language: java
jdk: oraclejdk8
branches:
  only:
  - master
before_install:
- docker version
- docker info
script:
- mvn clean verify -f alma-server/pom.xml -e
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker images
- docker push foorganization/alma-server:latest

deploy:
  provider: releases
  api_key: 86946d56927440e6bb57890cda836f4ceef633d5
  file: "alma-server-1.0.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
